### ISSUE TITLE
Lexicon 0.2 Roadmap.

### ISSUE THREAD

**Issue by MichaelHatherly** [MichaelHatherly/Lexicon.jl#109]
Planning issue for updating Lexicon.

- [ ] Switch from methods in ``Docile.Interface`` to ``Docile.Cache``.
- [ ] More coherent and detailed REPL display for docs.
- [ ] Clean up display of method signatures.
- [ ] Improve consistency of query system.
- [ ] Move to a separate query mode instead of replacing ``?``-mode.
- [ ] ``Compose.jl``-like API for creating static documentation.
- [ ] Modularise codebase, ``Query``, ``REPL``, ``Render``, ``Doctest``, etc.
- [ ] Improvements to ``doctest`` such as empty docstring checks, etc.
- [ ] Add additional ``metamacro`` definitions.

**Comment by peter1000** [comment]
hi,

I would be interested if you could share a bit what you have in mind for `Compose.jl-like API for creating static documentation.`

Anyway, I will busy for a couple of days otherwise so have a nice weekend.

**Comment by MichaelHatherly** [comment]
> Anyway, I will busy for a couple of days otherwise - so have a nice weekend.

Also totally snowed under right now, so I'll form my thoughts and get back to your question ASAP.

**Comment by MichaelHatherly** [comment]
> I would be interested if you could share a bit what you have in mind for Compose.jl-like API for creating static documentation.

What I mean is something like, in pseudocode:

```jl
other_pages = [page(m, title  = t,
                       filter = obj -> isa(obj, Function)) for (m, t) in things]

out =
    document(
        config(...),
        section(
            # The manual section of the documentation.
            config(...),
            page(...),
            page(...),
            section(...))
        section(
            # The function reference section.
            page(...),
            other_pages...))

save(pdf("out.pdf", out))
save(markdown("out", out))
...
```

``document`` creates a context in which we can set up a structure for the resulting documentation. 

``config`` would store things like ``title``, ``filter``, ``sorter``, etc. for modifying whatever it's applied to.

``section`` would be used to separate the documentation into different parts that could have different ``config`` settings. Can have sections within sections.

``page`` would contain either the contents of an external file, such as ``manual.md`` or the docstrings from a module, or group of modules.

``pdf`` would create an object suitable to save as a pdf. Similarly for ``markdown``, but as a folder rather than single file.

(Total vapour-ware at the moment though, so don't take this as a completed idea yet.)

**Comment by peter1000** [comment]
I did a small graph to get a feeling how that would/could look like based on a joined **Docile/Lexicon Documentation**. Did not add all Docile modules - just to get a feeling.


Added possible (Section, Page, Header, SubHeader) which are probably needed especially for a single pdf.

```
Docile/Lexicon combined Documentation Project
├── Manual  (Section)
│   ├── Overview  (Page)
│   │   ├── Installation  (Header)
│   │   ├── Overview  (Header)
│   │   ├── Backwards compatibility with julia 0.4's @doc  (Header)
│   │   ├── Viewing Documentation  (Header)
│   │   ├── Generating Documentation  (Header)
│   │   └── Doctests  (Header)
│   └── Syntax  (Page)
│       ├── Docstring Syntax   (Header)
│       │   ├── Syntax Summary  (SubHeader)
│       │   ├── @doc  (SubHeader)
│       │   └── Plain strings  (SubHeader)
│       └── Metamacro Syntax  (Header)
│           ├── Metamacros  (SubHeader)
│           ├── Metamacro Syntax  (SubHeader)
│           └── Metamacro definitions  (SubHeader)
└── API  (Section)
    ├── Docile  (SubSection)
    │   ├── Docile  (Page)
    │   │   └── Modules  (Header)
    │   ├── Cache  (Page)
    │   │   ├── Exported  (Header)
    │   │   │   └── Methods  (SubHeader)
    │   │   └── Internal  (Header)
    │   │       ├── Methods  (SubHeader)
    │   │       ├── Macros  (SubHeader)
    │   │       └── Aside  (SubHeader)
    │   └── Collector  (Page)
    │       └── Internal  (Header)
    │           ├── Functions  (SubHeader)
    │           ├── Methods  (SubHeader)
    │           ├── Types  (SubHeader)
    │           └── Aside  (SubHeader)
    └── Lexicon  (SubSection)
        ├── Exported  (Page)
        └── Internal  (Page)

```

One can easily see that the minimum required structure would be **(Document, Section, SubSection, Page, Header, SubHeader)**

Some of the `page, header` could be replaced by more `SubSubSections` but I think for a consistence display it would be better to plan for

* Document
* Section
* Page
* Header
* SubHeader

structure - which is quite similar to what I had in mind her:  [Propose new section meta](#103)

**Comment by peter1000** [comment]
BTW: I send you some thought about aside-comments to [gitter](https://gitter.im/MichaelHatherly/Docile.jl)

**Comment by MichaelHatherly** [comment]
We don't need `SubSection` since you can just put a `Section` inside another `Section`. Anything internal to a `Page` is part of the page, like `Header`, and so don't need to be "composed".

**Comment by peter1000** [comment]
> We don't need SubSection

Yes I know just wanted to put the structure out

> Anything internal to a Page is part of the page, like Header, and so don't need to be "composed".

I don't understand exactly what you mean by: `don't need to be "composed".`

> page would contain either the contents of an external file, such as manual.md or **the docstrings from a module, or group of modules.**

Seems to me that one has to somehow produce the right header with which ever group of objects one want below.

**Comment by MichaelHatherly** [comment]
> I don't understand exactly what you mean by: `don't need to be "composed".`

So say you have a `elem = page("manual.md")`. That's a single block of content that can be placed into a `document`. Being able to manipulate `elem` is unnecessary since it's just an external file that you can edit manually. Having multiple routes to modifying a single thing is unnecessary.

> Seems to me that one has to somehow produce the right header with which ever group of objects one want below.

That should be covered by `filter`, `sorter` and some additional options for specifying styling of entries.

**Comment by peter1000** [comment]
**Compose.jl-like API for creating static documentation.**

If you don't mind I would like to give this a try as I'm interested in it (REPL integration and such is not so much of interest to myself): just saying so we might not overlap too much.

**Comment by peter1000** [comment]
I plan to work next on this issues:

* [Show keyword arguments in generated output](https://github.com/MichaelHatherly/Lexicon.jl/issues/19)

* [Duplicate entries generated for methods with default arguments.](https://github.com/MichaelHatherly/Lexicon.jl/issues/17)

**Comment by peter1000** [comment]
I was wondering about the `docs` node which accepts `Union(AbstractString, Module))`

If you look at my [example](http://peter1000.github.io/new_lexicon_example_docs1/api/docile.collector/#external)

after appling the filter there where no objects for: **External - Modules, Functions, Methods & Macros**

**1.**
What do you think: should any `AbstractString` before a module only be printed if there are actual objects after filtering?

```julia
docs("### Modules, Functions, Methods & Macros", 
        Docile.Cache,
        filter = obj -> iscategory(Docile.Cache, obj, [:module, :function, :method, :macro])
       )
```

**2**
What should happen if there are multiple `modules` defined within one `docs`

```julia
docs("### Modules, Functions, Methods & Macros", 
        Docile.Cache,
        Docile.Collector,
        filter = obj -> iscategory(Docile.Cache, obj, [:module, :function, :method, :macro]) ||
                              iscategory(Docile.Collector, obj, [:module, :function, :method, :macro])
       )
```

Should all objects mixed together when sorting or each mosule by itself etc..

Or would it be better to allow only one module per `docs` - even make it mandatory?

**Comment by peter1000** [comment]
At the moment my own feeling for `docs` would be:

- allow only `modules` for docs - remove the `AbstractString`
- for an optional header text use a config: 

  e.g. `header = "### Modules, Functions, Methods & Macros"` 
  which is ony written if ther are actual objects after filtering.

- all other text can be done in the `page` node.
- still allow multiple modules but their objects get completely mixed per filter and sorter

**Comment by MichaelHatherly** [comment]
> What do you think: should any ``AbstractString`` before a module only be printed if there are actual objects after filtering?

I'd think it should stay. If you're building docs and you end up with a section with a header but no docs it's slightly more noticeable than a completely empty section.

> At the moment my own feeling for docs would be:

Give it a try if you'd like. I'm not sure a see the issue with interspersing strings and modules in ``docs`` though, but I'm happy go that route if we don't loose any features.

> multiple modules but their objects get completely mixed

Is mixing objects from different modules actually a good idea? If a project is so small then multiple modules probably isn't what should be used to start with.

**Comment by peter1000** [comment]
> I'd think it should stay. If you're building docs and you end up with a section with a header but no docs it's slightly more noticeable than a completely empty section.

Also true

If we keep them the other things are not really relevant ...

thanks

**Comment by peter1000** [comment]
hi,

just catched up with your work on the julia github. I think I skip a couple of days before restarting on Lexicon.... who knows what changes the julia doctransition might bring for Docile/Lexicon.

**Comment by MichaelHatherly** [comment]
Yes, lets rather wait. There may be a few things worth taking from our work here once things have settled on master. There's momentum at the moment so it's not really worth splitting effort.

**Comment by hayd** [comment]
To get to https://github.com/MichaelHatherly/Lexicon.jl/issues/109#issuecomment-102042683 / https://github.com/MichaelHatherly/Lexicon.jl/issues/109#issuecomment-102102835

As an alternative approach, if it exists read the `../mkdocs.yml` file (and accept passing of a yml of a different name), and extract the pages section e.g.

```
pages:
- Introduction: index.md
- Manual:
  - Overview: manual.md
- API:
  - Lexicon: api/Lexicon.md
  - Index: api/index.md
```

Boom. You have the structure for a pdf.

I think this would be easier/clearer what's going:

1 you generate markdown files
2a. you statically host
2b. include parsed/latexed markdown, using the above titles etc. -> pdf

**Comment by MichaelHatherly** [comment]
> As an alternative approach, if it exists read the ``../mkdocs.yml`` file (and accept passing of a yml of a different name), and extract the pages section e.g.

That would work nicely I think. Would be nice to have it more general than relying on mkdocs for that though. Since if mkdocs goes and changes their format, which I think has happened already, then that would break Lexicon.

**Comment by MichaelHatherly** [comment]
> create a big markdown file and just throw it to pandoc

Do you know what the licensing is like for pandoc? It's GLP I think, would that be a problem if bundled as a dep?

**Comment by hayd** [comment]
I wouldn't bother, you could just ask users install it, and shell out.... :/

all we'd need is a suitable  --include-in-header or --template. The default isn't great IMO.

**Comment by hayd** [comment]
Maybe outputting to gitbook is the way forward (I still favor doing this via _generated), IMO their pdf rendering looks *really* nice. see https://www.gitbook.com/book/gitbookio/documentation/details (since you mentioned this earlier).

**Comment by MichaelHatherly** [comment]
Yeah, gitbook is quite nice from what I've tried so far.

So long as we just output plain old markdown with the docstrings spliced in it shouldn't make a difference what anyone uses after that stage. I'd rather not become totally tied to some external package if we can help it.

**Comment by hayd** [comment]
That's the good thing about most of these tools, it's usually some file e.g. SUMMARY.md or mkdocs.yml which glues the markdown files together. One annoying part (of gitbook) is the showing of wide code blocks cuts off (IIUC it uses phantomjs to render, which can't scroll).

**Comment by peter1000** [comment]
> So long as we just output plain old markdown with the docstrings spliced in it shouldn't make a difference what anyone uses after that stage. 

:+1: 

hi Michael,

I saw you and one-more-minute merging quite a bit to julia master.  Could you just shortly update me on your thoughts:

1.  How does the new additions to julia effect Docile/Lexicon. Does not some of it overlap what Docile did? Do you plan to removed such from Docile/Lexicon source ...

2. Are you still planning to change to [exicon-next](https://github.com/MichaelHatherly/Lexicon.jl/tree/lexicon-next) ? I saw **hayd** has done some work / addition based on the 'old/current Lexicon'.

Cheers
P

**Comment by MichaelHatherly** [comment]
Does https://github.com/MichaelHatherly/Docile.jl/issues/147 answer some of you're questions? There's probably lots of more specialised things that the base docsystem doesn't need to cover which can be left to Docile/Lexicon.

> I saw hayd has done some work / addition based on the 'old/current Lexicon'.

Hadn't noticed the branch that was against. It's fine though if it turns out to be a minor addition then getting it into a tagged release would be easier than having it on ``lexicon-next``.

**Comment by peter1000** [comment]
> Does MichaelHatherly/Docile.jl#147 answer some of you're questions? 

Yes. Thanks I had not seen that.

**Comment by hayd** [comment]
Also there's the rewrite branch. My PR was pretty independent. :s

**Comment by MichaelHatherly** [comment]
> Also there's the rewrite branch.

Not sure what I was thinking when creating yet another branch... ignore that one for the moment I think.

**Comment by hayd** [comment]
If we thought the generate_for api was a good one, I would suggest that the api files should generate something parsable (i.e. intermediary markdown which includes the `{{}}` syntax) that can be hit with `@file`. Thoughts?

I think this would mean

1. bringing in all features build doesn't have yet.
2. separate docstring rendering of methods that do not share docstrings. (Would use this always).
3. be able to do it based on types (e.g. you may be interested in a methods on TypeA in one page, and TypeB in another). IIUC This wouldn't be necessary if you used submodules. Not required at first.

I think the API, at it's simplest would remain:

    generate_for(Lexicon, "index.md", ...)

perhaps with a kwarg to (not) build and `@file` the api markdown files for `submodules(Lexicon)`, and a kwarg for `no_submodules` (IIRC you have a better name for that).

**Comment by MichaelHatherly** [comment]
> I would suggest that the api files should generate something parsable

Could you provide an example of what you mean by this? Just markdown files containing ``{{}}`` that expand into the ``@file`` macro calls?

> ```
> generate_for(Lexicon, "index.md", ...)
> ```

Naming-wise would ``build``, ``save``, or ``generate`` sound better instead?

**Comment by hayd** [comment]
e.g. generate api/Lexicon.md as:
```
# Lexicon

## Exported

{{
  doctest
  query
  save
  Config
  EachEntry
  @query
}}

## Internal

{{
  calculate_score
  ...
}}
```
This *could* be done temporarily i.e. generate `_temp/api/Lexicon.md` apply `@file` to this into `_generated/api/Lexicon.md` (maybe) remove the temp file.

Similarly for (API-)Index.md.

Make sense?

---

I like readability of `generate_for`, "generate for Lexicon the following files", I don't think brevity is important in naming here. :/

**Comment by peter1000** [comment]
I don't mind much about `generate, build, save` vs. `generate_for` but  in my past experience *MichaelHatherly* doesn't like the underscore _for part. 

Considering the present and the lexicon-next situation I think `save` would be the most appropriate one but `generate` is also good as a tempfile is suggested to be generated.

**Comment by hayd** [comment]
I guess I'd be *okay* with generate, I really dislike "save" for this (that kinda makes sense for creating a single page - from the generated markdowns, or for creating a mkdocs.yml\*)

\* would make more sense if generate accepted `Pair`s (of filename => title).
